### ISSUE TITLE
仓库缺少io.shulie:druid的指定版本的包

### ISSUE THREAD

**Issue by xianwq** [shulieTech/LinkAgent#13]
odule-pradar-core中的这个依赖，io.shulie:druid，远程仓库没有版本为1.2.5的包

![image](https://user-images.githubusercontent.com/45792060/123541571-cfa96f80-d777-11eb-9e6e-ef3aac607e14.png)

![image](https://user-images.githubusercontent.com/45792060/123541620-08494900-d778-11eb-9538-67b54491c8af.png)

辛苦把1.2.5的版本传到远程仓库

**Comment by shulieTech** [comment]
已经传输到中央仓库，预计明天可以正常拉取。

**Comment by jirenhe** [comment]
已可以拉取
