### ISSUE TITLE
visible: instrument-simulator

### ISSUE THREAD

**Issue by ZhangTianCi** [shulieTech/LinkAgent#16]
The folder name is different whit the 'pom.xml > artifactId & name'.

It doesn't look good in IntelliJ IDEA.

![image](https://user-images.githubusercontent.com/10275488/124207863-f7eaf280-db18-11eb-8731-a1111da25704.png)

**Comment by yriiolik** [comment]
right。。。 there is tree maven project in LinkAgent，  not  one maven projetct + 3 modules 。。。
