### ISSUE TITLE
module-pradar-config-fetcher 从服务端获取白名单列表 地址好像不太对

### ISSUE THREAD

**Issue by Mrchenli** [shulieTech/LinkAgent#17]
![image](https://user-images.githubusercontent.com/20294244/124573207-e9376f00-de7b-11eb-9977-37268071e827.png)
调整url后注册正常

**Comment by Mrchenli** [comment]
![image](https://user-images.githubusercontent.com/20294244/124573412-197f0d80-de7c-11eb-8e54-702720921b38.png)

**Comment by yriiolik** [comment]
报的是什么错误呢？  404么？

**Comment by Mrchenli** [comment]
哦哦 这样我就懂啦  我把组件拆分出来啦，没用ng , 所以是404。
