### ISSUE TITLE
影子key压测数据过期时间增强点的疑问

### ISSUE THREAD

**Issue by 15898317421** [shulieTech/LinkAgent#20]
private EnhanceCallback pluginMaxRedisExpireTimeCallback = new EnhanceCallback() {
        @Override
        public void doEnhance(InstrumentClass target) {

            InstrumentMethod method = target.getDeclaredMethods("expire","pexpire","setex","psetex");
            method.addInterceptor(Listeners
                .of(PluginMaxRedisExpireTimeInterceptor.class));
            target.getDeclaredMethod("set","java.lang.Object","java.lang.Object","io.lettuce.core.SetArgs")
                .addInterceptor(Listeners.of(PluginMaxRedisExpireTimeInterceptor.class));
        }
    };
这段代码好像只对5个方法做了过期时间，是还有其他的入口吗？

**Comment by JiangJibo** [comment]
没有了
