### ISSUE TITLE
unload时不会从cache中删除Module 的ClassLoaderFactory

### ISSUE THREAD

**Issue by zfyq124** [shulieTech/LinkAgent#21]
unload时不会从cache中删除Module 的ClassLoaderFactory，重新load Module时获取的ClassLoaderFactory依然是老的ClassLoaderFactory。旧的ClassLoader在unload时会卸已加载的类与资源导致后续加载资源不正常影响后续流程

如重新loade module时使用旧的ClassLoaderFactory不会加载spi规范的文件，load不正常
![image](https://user-images.githubusercontent.com/5370955/126777174-f1e673f8-c7bc-414e-a541-117c3ab2e334.png)

**Comment by yriiolik** [comment]
在 classLoaderService 里面，上一次卸载插件的时候会清除 ClassLoaderFactory 缓存哦。

**Comment by zfyq124** [comment]
现在卸载插件时只会清除ClassLoaderFactory与导出类与导出资源的关联关系，但不会从 moduleClassLoaderMap 中删除。导致下次加载时使用的ClassLoaderFactory依然存在，旧的ClassLoaderFactory中关联的ClassLoader已经在卸载时尝试删除一些资源了

如初始加载dbcp2时将ClassLoaderFactory放在了cache中
![image](https://user-images.githubusercontent.com/5370955/126948435-6c1222f7-e889-4334-a254-2e5ede4819f0.png)

卸载dbcp2，再重新加载dbcp2, 此时moduleClassLoaderMap中依然是
![image](https://user-images.githubusercontent.com/5370955/126949199-f341f9d4-77eb-4e27-b5d0-81724de3dbc0.png)


再重新加载资源时因为ClassLoaderFactory中对应的ClassLoader中的资源已经被卸载导致资源加载不到，因为旧的ClassLoader已经卸载了一些资源
![image](https://user-images.githubusercontent.com/5370955/126949586-0c57ae35-6d4c-4f5d-ba0c-aa3cc558d4ee.png)

现在模块卸载后ClassLoaderService中的缓存一个Module会对应多个ClassLoaderFactory

**Comment by yriiolik** [comment]
你是指定卸载 dbcp2 这个模块吧？  最终的缓存在 DefaultClassLoaderService 中。  

目前单独卸载/加载模块的功能还未完全开发完。  目前支持的是卸载 instrument-simulator 和 所有modules， 然后重新加载  instrument-simulator 和 所有modules。  

细粒度的模块加载卸载将在未来的版本中增加。
