### ISSUE TITLE
com.pamirs.attach.plugin.netty.job.obj.TraceTimerTask 方法增强有bug，会报空指针

### ISSUE THREAD

**Issue by spjich** [shulieTech/LinkAgent#300]
com.pamirs.attach.plugin.netty.job.obj.TraceTimerTask 方法增强有bug，会报空指针

![image](https://user-images.githubusercontent.com/18671171/180171786-06d85444-064d-4f6f-a9a3-d9a5788ac611.png)
![image](https://user-images.githubusercontent.com/18671171/180171868-cae1cc10-027a-4557-87d7-60469c0fbf16.png)

**Comment by JiangJibo** [comment]
应该修复这个问题了
