### ISSUE TITLE
module-pradar-core构建失败，io.shulie.instrument.module:dependency-processor:jar:1.2 依赖缺失

### ISSUE THREAD

**Issue by hankzhao81** [shulieTech/LinkAgent#522]
基于main分支构建，这个坐标io.shulie.instrument.module:dependency-processor:jar:1.2 maven repo是找不到
<img width="941" alt="image" src="https://github.com/shulieTech/LinkAgent/assets/51235192/046d3e90-131c-4e7a-afca-8351cf8f7846">

**Comment by JiangJibo** [comment]
这是一个私有的依赖工程，可以在我们微信群里@下管理人员，我把源码发给你

**Comment by JiangJibo** [comment]
关闭
