### ISSUE TITLE
发起正常业务流程时，探针报空指针异常，导致远程调用一直没有对应接口数据

### ISSUE THREAD

**Issue by huchunyong1987** [shulieTech/LinkAgent#57]
在应用上报成功之后，发起正常业务流程时，探针报空指针异常（见下图1），导致远程调用一直没有对应接口数据。现在这个问题是个阻断性问题，需要尽快解决。图1:
![image](https://user-images.githubusercontent.com/41766973/143518979-5f1ca6f7-9e45-4c57-b2ec-5e07bc68a0b9.png)
发起压测流量时，在被压测的应用里，也还会报类型转换异常（见下图2）。图2:
![image](https://user-images.githubusercontent.com/41766973/143519128-fca7217b-2435-4443-9ab7-b94b4e6671be.png)

**Comment by jirenhe** [comment]
第一个问题已修复，代码已经提交了， 重新拉下代码打包试试
第二个问题正在修复中，预计下周解决

**Comment by VernonMin** [comment]
> ![image](https://user-images.githubusercontent.com/41766973/143519128-fca7217b-2435-4443-9ab7-b94b4e6671be.png)

第二个问题已经修复，重新拉下代码试试。

**Comment by huchunyong1987** [comment]
> > ![image](https://user-images.githubusercontent.com/41766973/143519128-fca7217b-2435-4443-9ab7-b94b4e6671be.png)
> 
> 第二个问题已经修复，重新拉下代码试试。

好的,感谢各位大佬
