### ISSUE TITLE
CommandChannelPlugin 编译异常

### ISSUE THREAD

**Issue by buzuotaxuan** [shulieTech/LinkAgent#76]
![image](https://user-images.githubusercontent.com/11420694/146511338-c4ae39dc-02d3-4689-90d8-7f4d6d80189a.png)

**Comment by jsfbetter** [comment]
能加个好友吗？我也在编译

**Comment by jsfbetter** [comment]
你用的哪个分支

**Comment by jsfbetter** [comment]
我用featrure/5.3.0.0.,报错是
![image](https://user-images.githubusercontent.com/17878613/155492464-8dd4552a-a321-45ca-a6f0-fd7f0ad72923.png)

**Comment by lqxandxl** [comment]
我也遇到了，另外          io.shulie.instrument.module ：  simulator-bootstrap-api 也没有找到。

io.shulie.takin：takin-common-command-channel ：common-2.0.0.0-SNAPSHOT 也没有找到。 希望官方可以在maven仓库中添加相关依赖。

**Comment by JiangJibo** [comment]
在微信群里找管理人员
